In [1]:
# Importing Dependencies
import pandas as pd
import numpy as np

In [2]:
# Bringing in Uncleaned CSV's
csv1 = "Resources/Sep2019-citibike-tripdata.csv"
csv2 = "Resources/Sep2020-citibike-tripdata.csv"
bike_trip_2019 = pd.read_csv(csv1)
bike_trip_2020 = pd.read_csv(csv2)

In [3]:
# Viewing the 2019 Data
bike_2019_df = bike_trip_2019
bike_2019_df.head(2)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,327,2019-09-01 00:00:01.9580,2019-09-01 00:05:29.3410,3733,Avenue C & E 18 St,40.730563,-73.973984,504,1 Ave & E 16 St,40.732219,-73.981656,39213,Subscriber,1968,1
1,1145,2019-09-01 00:00:04.1430,2019-09-01 00:19:09.8360,3329,Degraw St & Smith St,40.682915,-73.993182,270,Adelphi St & Myrtle Ave,40.693083,-73.971789,21257,Customer,1969,0

In [4]:
# Viewing the 2020 Data
bike_2020_df = bike_trip_2020
bike_2020_df.head(2)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,4225,2020-09-01 00:00:01.0430,2020-09-01 01:10:26.6350,3508,St Nicholas Ave & Manhattan Ave,40.809725,-73.953149,116,W 17 St & 8 Ave,40.741776,-74.001497,44317,Customer,1979,1
1,1868,2020-09-01 00:00:04.8320,2020-09-01 00:31:13.7650,3621,27 Ave & 9 St,40.773983,-73.930913,3094,Graham Ave & Withers St,40.716981,-73.944859,37793,Customer,1991,1

In [5]:
# Deleting Columns
del bike_2019_df['usertype']
del bike_2020_df['usertype']

In [6]:
bike_2019_df.head(5)
bike_2020_df.head(5)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,birth year,gender
0,4225,2020-09-01 00:00:01.0430,2020-09-01 01:10:26.6350,3508,St Nicholas Ave & Manhattan Ave,40.809725,-73.953149,116,W 17 St & 8 Ave,40.741776,-74.001497,44317,1979,1
1,1868,2020-09-01 00:00:04.8320,2020-09-01 00:31:13.7650,3621,27 Ave & 9 St,40.773983,-73.930913,3094,Graham Ave & Withers St,40.716981,-73.944859,37793,1991,1
2,1097,2020-09-01 00:00:06.8990,2020-09-01 00:18:24.2260,3492,E 118 St & Park Ave,40.800539,-73.941995,3959,Edgecombe Ave & W 145 St,40.823498,-73.943860,41438,1984,1
3,1473,2020-09-01 00:00:07.7440,2020-09-01 00:24:41.1800,3946,St Nicholas Ave & W 137 St,40.818477,-73.947568,4002,W 144 St & Adam Clayton Powell Blvd,40.820877,-73.939249,35860,1990,2
4,1193,2020-09-01 00:00:12.2020,2020-09-01 00:20:05.5470,3081,Graham Ave & Grand St,40.711863,-73.944024,3048,Putnam Ave & Nostrand Ave,40.684020,-73.949770,26396,1969,0

In [7]:
# Checking Type of Values
bike_2019_df.dtypes
bike_2020_df.dtypes

tripduration                 int64
starttime                   object
stoptime                    object
start station id             int64
start station name          object
start station latitude     float64
start station longitude    float64
end station id               int64
end station name            object
end station latitude       float64
end station longitude      float64
bikeid                       int64
birth year                   int64
gender                       int64
dtype: object

In [8]:
# Changing The Type of Values for the Gender Column
bike_2019_df['gender'] = bike_2019_df['gender'].astype(str)
bike_2020_df['gender'] = bike_2020_df['gender'].astype(str)

In [9]:
# Changing the Numeric Gender Values to Actual Gender Values For The 2019 CSV
gender_check_2019 = bike_2019_df['gender']
changed_2019_male = gender_check_2019.replace('1', 'Male')
changed_2019_female = changed_2019_male.replace('2', 'Female')
changed_2019_unknown = changed_2019_female.replace('0', 'Unknown')
bike_2019_df['gender'] = changed_2019_unknown
bike_2019_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,birth year,gender
0,327,2019-09-01 00:00:01.9580,2019-09-01 00:05:29.3410,3733,Avenue C & E 18 St,40.730563,-73.973984,504,1 Ave & E 16 St,40.732219,-73.981656,39213,1968,Male
1,1145,2019-09-01 00:00:04.1430,2019-09-01 00:19:09.8360,3329,Degraw St & Smith St,40.682915,-73.993182,270,Adelphi St & Myrtle Ave,40.693083,-73.971789,21257,1969,Unknown
2,1293,2019-09-01 00:00:07.3090,2019-09-01 00:21:40.7580,3168,Central Park West & W 85 St,40.784727,-73.969617,423,W 54 St & 9 Ave,40.765849,-73.986905,15242,1969,Unknown
3,1753,2019-09-01 00:00:08.0640,2019-09-01 00:29:21.5040,3299,E 98 St & Park Ave,40.788130,-73.952060,3160,Central Park West & W 76 St,40.778968,-73.973747,38760,1990,Male
4,613,2019-09-01 00:00:12.8510,2019-09-01 00:10:26.1850,486,Broadway & W 29 St,40.746201,-73.988557,478,11 Ave & W 41 St,40.760301,-73.998842,32094,1992,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2444895,1764,2019-09-30 23:59:22.7670,2019-10-01 00:28:47.3180,3314,W 95 St & Broadway,40.793770,-73.971888,3161,W 76 St & Columbus Ave,40.780184,-73.977285,41516,1995,Male
2444896,378,2019-09-30 23:59:27.9270,2019-10-01 00:05:46.5700,316,Fulton St & William St,40.709560,-74.006536,327,Vesey Pl & River Terrace,40.715338,-74.016584,31124,1959,Female
2444897,561,2019-09-30 23:59:29.1450,2019-10-01 00:08:50.8070,3260,Mercer St & Bleecker St,40.727064,-73.996621,393,E 5 St & Avenue C,40.722992,-73.979955,30285,1998,Male
2444898,311,2019-09-30 23:59:42.2520,2019-10-01 00:04:54.2320,3746,6 Ave & Broome St,40.724308,-74.004730,3435,Grand St & Elizabeth St,40.718822,-73.995960,38290,1989,Male
2444899,1500,2019-09-30 23:59:55.3740,2019-10-01 00:24:55.8400,331,Pike St & Monroe St,40.711731,-73.991930,2012,E 27 St & 1 Ave,40.739445,-73.976806,34013,1969,Unknown

In [10]:
# Changing the Numeric Gender Values to Actual Gender Values For The 2020 CSV
gender_check_2020 = bike_2020_df['gender']
changed_2020_male = gender_check_2020.replace('1', 'Male')
changed_2020_female = changed_2020_male.replace('2', 'Female')
changed_2020_unknown = changed_2020_female.replace('0', 'Unknown')
bike_2020_df['gender'] = changed_2020_unknown
bike_2020_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,birth year,gender
0,4225,2020-09-01 00:00:01.0430,2020-09-01 01:10:26.6350,3508,St Nicholas Ave & Manhattan Ave,40.809725,-73.953149,116,W 17 St & 8 Ave,40.741776,-74.001497,44317,1979,Male
1,1868,2020-09-01 00:00:04.8320,2020-09-01 00:31:13.7650,3621,27 Ave & 9 St,40.773983,-73.930913,3094,Graham Ave & Withers St,40.716981,-73.944859,37793,1991,Male
2,1097,2020-09-01 00:00:06.8990,2020-09-01 00:18:24.2260,3492,E 118 St & Park Ave,40.800539,-73.941995,3959,Edgecombe Ave & W 145 St,40.823498,-73.943860,41438,1984,Male
3,1473,2020-09-01 00:00:07.7440,2020-09-01 00:24:41.1800,3946,St Nicholas Ave & W 137 St,40.818477,-73.947568,4002,W 144 St & Adam Clayton Powell Blvd,40.820877,-73.939249,35860,1990,Female
4,1193,2020-09-01 00:00:12.2020,2020-09-01 00:20:05.5470,3081,Graham Ave & Grand St,40.711863,-73.944024,3048,Putnam Ave & Nostrand Ave,40.684020,-73.949770,26396,1969,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2488220,1818,2020-09-30 23:59:48.8460,2020-10-01 00:30:07.7810,284,Greenwich Ave & 8 Ave,40.739017,-74.002638,3836,Bushwick Ave & Linden St,40.691460,-73.921460,36220,1993,Male
2488221,1553,2020-09-30 23:59:53.7240,2020-10-01 00:25:47.1760,390,Duffield St & Willoughby St,40.692216,-73.984284,3799,6 Ave & W 34 St,40.749640,-73.988050,31092,1995,Male
2488222,626,2020-09-30 23:59:54.6670,2020-10-01 00:10:21.6050,3901,Stanhope St & Fairview Ave,40.709980,-73.911160,3083,Bushwick Ave & Powers St,40.712477,-73.941000,47224,1954,Female
2488223,325,2020-09-30 23:59:56.2120,2020-10-01 00:05:21.3060,3148,E 84 St & 1 Ave,40.775655,-73.950686,3338,2 Ave & E 99 St,40.786259,-73.945526,16759,1995,Female
2488224,128,2020-09-30 23:59:57.8350,2020-10-01 00:02:06.0920,439,E 4 St & 2 Ave,40.726281,-73.989780,312,Allen St & Stanton St,40.722055,-73.989111,47718,1996,Female

In [11]:
# Calculating Biker's Age 
current_year = 2020

birth_year_2019 = bike_2019_df['birth year']
age = current_year - birth_year_2019
bike_2019_df['age'] = age

birth_year_2020 = bike_2020_df['birth year']
age = current_year - birth_year_2020
bike_2020_df['age'] = age

In [12]:
# Rearranging the Columns
bike_2019_df_organized = bike_2019_df[["bikeid",
                                       "gender",
                                       "birth year",
                                       "age",
                                       "tripduration",
                                       "start station id",
                                       "start station name",
                                       "start station latitude",
                                       "start station longitude",
                                       "starttime",
                                       "end station id",
                                       "end station name", 
                                       "end station latitude",
                                       "end station longitude",
                                       "stoptime"]]

bike_2020_df_organized = bike_2020_df[["bikeid",
                                       "gender",
                                       "birth year",
                                       "age",
                                       "tripduration",
                                       "start station id",
                                       "start station name",
                                       "start station latitude",
                                       "start station longitude",
                                       "starttime",
                                       "end station id",
                                       "end station name", 
                                       "end station latitude",
                                       "end station longitude",
                                       "stoptime"]]

bike_2019_df_organized.head(5)
bike_2020_df_organized.head(5)

,bikeid,gender,birth year,age,tripduration,start station id,start station name,start station latitude,start station longitude,starttime,end station id,end station name,end station latitude,end station longitude,stoptime
0,44317,Male,1979,41,4225,3508,St Nicholas Ave & Manhattan Ave,40.809725,-73.953149,2020-09-01 00:00:01.0430,116,W 17 St & 8 Ave,40.741776,-74.001497,2020-09-01 01:10:26.6350
1,37793,Male,1991,29,1868,3621,27 Ave & 9 St,40.773983,-73.930913,2020-09-01 00:00:04.8320,3094,Graham Ave & Withers St,40.716981,-73.944859,2020-09-01 00:31:13.7650
2,41438,Male,1984,36,1097,3492,E 118 St & Park Ave,40.800539,-73.941995,2020-09-01 00:00:06.8990,3959,Edgecombe Ave & W 145 St,40.823498,-73.943860,2020-09-01 00:18:24.2260
3,35860,Female,1990,30,1473,3946,St Nicholas Ave & W 137 St,40.818477,-73.947568,2020-09-01 00:00:07.7440,4002,W 144 St & Adam Clayton Powell Blvd,40.820877,-73.939249,2020-09-01 00:24:41.1800
4,26396,Unknown,1969,51,1193,3081,Graham Ave & Grand St,40.711863,-73.944024,2020-09-01 00:00:12.2020,3048,Putnam Ave & Nostrand Ave,40.684020,-73.949770,2020-09-01 00:20:05.5470

In [13]:
# Renaming the Columns
bike_2019_renamed_df = bike_2019_df_organized.rename(columns={"bikeid":"Bike ID", 
                                                              "gender":"Gender",
                                                              "birth year":"Birth Year",
                                                              "age":"Age",
                                                              "tripduration":"Trip Duration",
                                                              "start station id":"Start Station ID",
                                                              "start station name":"Start Station Name",
                                                              "start station latitude":"Start Station Latitude",
                                                              "start station longitude":"Start Station Longitude",
                                                              "starttime":"Start Time",
                                                              "end station id":"End Station ID",
                                                              "end station name":"End Station Name",
                                                              "end station latitude":"End Station Latitude",
                                                              "end station longitude":"End Station Longitude",
                                                              "stoptime":"Stop Time"})

bike_2020_renamed_df = bike_2020_df_organized.rename(columns={"bikeid":"Bike ID", 
                                                              "gender":"Gender",
                                                              "birth year":"Birth Year",
                                                              "age":"Age",
                                                              "tripduration":"Trip Duration",
                                                              "start station id":"Start Station ID",
                                                              "start station name":"Start Station Name",
                                                              "start station latitude":"Start Station Latitude",
                                                              "start station longitude":"Start Station Longitude",
                                                              "starttime":"Start Time",
                                                              "end station id":"End Station ID",
                                                              "end station name":"End Station Name",
                                                              "end station latitude":"End Station Latitude",
                                                              "end station longitude":"End Station Longitude",
                                                              "stoptime":"Stop Time"})



bike_2019_renamed_df
bike_2020_renamed_df

,Bike ID,Gender,Birth Year,Age,Trip Duration,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,Start Time,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Stop Time
0,44317,Male,1979,41,4225,3508,St Nicholas Ave & Manhattan Ave,40.809725,-73.953149,2020-09-01 00:00:01.0430,116,W 17 St & 8 Ave,40.741776,-74.001497,2020-09-01 01:10:26.6350
1,37793,Male,1991,29,1868,3621,27 Ave & 9 St,40.773983,-73.930913,2020-09-01 00:00:04.8320,3094,Graham Ave & Withers St,40.716981,-73.944859,2020-09-01 00:31:13.7650
2,41438,Male,1984,36,1097,3492,E 118 St & Park Ave,40.800539,-73.941995,2020-09-01 00:00:06.8990,3959,Edgecombe Ave & W 145 St,40.823498,-73.943860,2020-09-01 00:18:24.2260
3,35860,Female,1990,30,1473,3946,St Nicholas Ave & W 137 St,40.818477,-73.947568,2020-09-01 00:00:07.7440,4002,W 144 St & Adam Clayton Powell Blvd,40.820877,-73.939249,2020-09-01 00:24:41.1800
4,26396,Unknown,1969,51,1193,3081,Graham Ave & Grand St,40.711863,-73.944024,2020-09-01 00:00:12.2020,3048,Putnam Ave & Nostrand Ave,40.684020,-73.949770,2020-09-01 00:20:05.5470
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2488220,36220,Male,1993,27,1818,284,Greenwich Ave & 8 Ave,40.739017,-74.002638,2020-09-30 23:59:48.8460,3836,Bushwick Ave & Linden St,40.691460,-73.921460,2020-10-01 00:30:07.7810
2488221,31092,Male,1995,25,1553,390,Duffield St & Willoughby St,40.692216,-73.984284,2020-09-30 23:59:53.7240,3799,6 Ave & W 34 St,40.749640,-73.988050,2020-10-01 00:25:47.1760
2488222,47224,Female,1954,66,626,3901,Stanhope St & Fairview Ave,40.709980,-73.911160,2020-09-30 23:59:54.6670,3083,Bushwick Ave & Powers St,40.712477,-73.941000,2020-10-01 00:10:21.6050
2488223,16759,Female,1995,25,325,3148,E 84 St & 1 Ave,40.775655,-73.950686,2020-09-30 23:59:56.2120,3338,2 Ave & E 99 St,40.786259,-73.945526,2020-10-01 00:05:21.3060
2488224,47718,Female,1996,24,128,439,E 4 St & 2 Ave,40.726281,-73.989780,2020-09-30 23:59:57.8350,312,Allen St & Stanton St,40.722055,-73.989111,2020-10-01 00:02:06.0920

In [14]:
# write both cleaned files as csv into Output folder
bike_2019_renamed_df.to_csv("Output/Sep2019-citibike_tripdata_cleaned.csv", index=False, header=True)
bike_2020_renamed_df.to_csv("Output/Sep2020citibike_tripdata_cleaned.csv", index=False, header=True)